# Generated by Django 5.0.14 on 2025-12-04 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_account', '0002_alter_botauth_jwt_token_alter_botauth_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuteCursCbr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nominal', models.IntegerField(blank=True, default=0)),
                ('value', models.FloatField(blank=True, default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CollectorQuoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_bonds', models.CharField(max_length=100)),
                ('symbol_futures', models.CharField(max_length=100)),
                ('auth_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.botauth')),
                ('cbr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector_app.valutecurscbr')),
            ],
        ),
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last', models.FloatField(blank=True, default=0)),
                ('ask', models.FloatField(blank=True, default=0)),
                ('bid', models.FloatField(blank=True, default=0)),
                ('last1', models.FloatField(blank=True, default=0)),
                ('ask1', models.FloatField(blank=True, default=0)),
                ('bid1', models.FloatField(blank=True, default=0)),
                ('last2', models.FloatField(blank=True, default=0)),
                ('ask2', models.FloatField(blank=True, default=0)),
                ('bid2', models.FloatField(blank=True, default=0)),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector_app.collectorquoter')),
            ],
        ),
    ]
