# Generated by Django 5.0.14 on 2025-12-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='cbr_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
