# Generated by Django 5.0.14 on 2025-12-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0003_bar_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='valutecurscbr',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
