# Generated by Django 5.0.14 on 2025-12-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0004_valutecurscbr_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorquoter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
