# Generated by Django 5.0.14 on 2025-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0005_collectorquoter_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectorquoter',
            name='nominal_bonds',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='collectorquoter',
            name='nominal_futures',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
