# Generated by Django 5.0.14 on 2025-12-07 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0006_collectorquoter_nominal_bonds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCbr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day1', models.IntegerField(blank=True, default=0)),
                ('hour1', models.IntegerField(blank=True, default=0)),
                ('last1', models.FloatField(blank=True, default=0)),
                ('day2', models.IntegerField(blank=True, default=0)),
                ('hour2', models.IntegerField(blank=True, default=0)),
                ('last2', models.FloatField(blank=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cbr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='collector_app.valutecurscbr')),
            ],
        ),
    ]
