# Generated by Django 5.0.14 on 2025-12-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0007_barcbr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='barcbr',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='barcbr',
            name='last',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
