# Generated by Django 5.0.14 on 2025-12-07 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0008_alter_bar_options_alter_barcbr_options_barcbr_last'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bar',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='barcbr',
            options={'ordering': ['created_at']},
        ),
    ]
