# Generated by Django 5.0.14 on 2025-12-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0009_alter_bar_options_alter_barcbr_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarCbrDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('year', models.IntegerField(blank=True, default=0)),
                ('month', models.IntegerField(blank=True, default=0)),
                ('day', models.IntegerField(blank=True, default=0)),
                ('price', models.FloatField(blank=True, default=0)),
                ('cbr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collector_app.valutecurscbr')),
            ],
        ),
    ]
