# Generated by Django 5.0.14 on 2025-12-22 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0010_barcbrday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barcbrday',
            options={'ordering': ['timestamp']},
        ),
    ]
