# Generated by Django 5.0.14 on 2025-12-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector_app', '0011_alter_barcbrday_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='barcbrday',
            name='date_str',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
