# Generated by Django 5.0.14 on 2026-01-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_account', '0002_alter_botauth_jwt_token_alter_botauth_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQuoterOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('auth_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.botauth')),
            ],
        ),
    ]
