# Generated by Django 5.0.14 on 2026-01-09 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_account', '0002_alter_botauth_jwt_token_alter_botauth_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQuoterSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('symbolA', models.CharField(max_length=100)),
                ('symbolB', models.CharField(max_length=100)),
                ('symbolC', models.CharField(max_length=100)),
                ('symbolCB', models.CharField(max_length=100)),
                ('sideCB', models.CharField(choices=[('b', 'b'), ('s', 's'), ('n', 'n')], help_text='side', max_length=30)),
                ('quantityB', models.FloatField(default=0)),
                ('quantityC', models.FloatField(default=0)),
                ('quantityCB', models.FloatField(default=0)),
                ('step_price', models.FloatField(default=0)),
                ('step_quantity', models.FloatField(default=0)),
                ('max_quantity', models.FloatField(default=0)),
                ('ask', models.FloatField(blank=True, default=0, null=True)),
                ('last', models.FloatField(blank=True, default=0, null=True)),
                ('bid', models.FloatField(blank=True, default=0, null=True)),
                ('ema', models.FloatField(blank=True, default=0, null=True)),
                ('auth_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.botauth')),
            ],
        ),
    ]
