# Generated by Django 5.0.14 on 2026-01-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread_quoter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSmartSpread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.IntegerField(blank=True, default=0)),
                ('level_queue', models.IntegerField(blank=True, default=0)),
                ('level_price', models.FloatField(blank=True, default=0, null=True)),
                ('level_side', models.CharField(choices=[('b', 'b'), ('s', 's')], help_text='side', max_length=30)),
                ('level_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('client_order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('side', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('limit_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spread_quoter.botquoterspread')),
            ],
            options={
                'ordering': ('level_id',),
            },
        ),
    ]
