# Generated by Django 5.0.14 on 2026-01-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spread_quoter', '0002_ordersmartspread'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmartspread',
            name='level_step',
            field=models.FloatField(default=0),
        ),
    ]
