# Generated by Django 5.0.14 on 2025-12-02 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotQuoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=100)),
                ('step_price', models.FloatField(default=0)),
                ('quantity_max', models.FloatField(blank=True, default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('side', models.CharField(blank=True, choices=[('b', 'b'), ('s', 's'), ('n', 'n')], default='n', help_text='side', max_length=3, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
                ('ask', models.FloatField(blank=True, default=0, null=True)),
                ('last', models.FloatField(blank=True, default=0, null=True)),
                ('bid', models.FloatField(blank=True, default=0, null=True)),
                ('auth_bot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_account.botauth')),
            ],
        ),
        migrations.CreateModel(
            name='OrderQuoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('level_id', models.IntegerField(blank=True, default=0)),
                ('level_queue', models.IntegerField(blank=True, default=0)),
                ('level_price', models.FloatField(blank=True, default=0, null=True)),
                ('level_range', models.FloatField(blank=True, default=0)),
                ('level_side', models.CharField(choices=[('b', 'b'), ('s', 's')], help_text='side', max_length=30)),
                ('level_quantity', models.FloatField(blank=True, default=0, null=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('order_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('side', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('limit_price', models.FloatField(blank=True, default=0, null=True)),
                ('quantity', models.FloatField(blank=True, default=0, null=True)),
                ('bot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bund_quoter.botquoter')),
            ],
            options={
                'ordering': ('level_id',),
            },
        ),
    ]
