# Generated by Django 5.0.14 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('secret_key', models.TextField(blank=True, default='', null=True)),
                ('jwt_token', models.TextField()),
            ],
        ),
    ]
