# Generated by Django 5.0.14 on 2025-12-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botauth',
            name='jwt_token',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='botauth',
            name='secret_key',
            field=models.TextField(),
        ),
    ]
